version: "3.7"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'unless-stopped'
    networks:
      - backend
    volumes:
      - .:/srv
    ports:
      - 8000:80
    command: uvicorn --host=0.0.0.0 --port 80 app.main:app --reload
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:11
    restart: 'unless-stopped'
    networks:
      - backend
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=api
    volumes:
      - /var/tmp/pg_db_temp:/var/lib/postgresql/data/
    ports:
      - 5432:5432

networks:
  backend:
